# Generated by Django 4.2 on 2024-10-15 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='setorganizationadmin',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='setorganizationadmin',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='setorganizationadmin',
            name='organization',
        ),
        migrations.AddField(
            model_name='historicalorganizations',
            name='admin',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizations',
            name='admin',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='HistoricalSetOrganizationAdmin',
        ),
        migrations.DeleteModel(
            name='SetOrganizationAdmin',
        ),
    ]
