# Generated by Django 4.2 on 2024-10-24 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_setorganizationadmin_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorganizations',
            name='education_type',
            field=models.CharField(choices=[("Maktabgacha ta'lim", "Maktabgacha ta'lim"), ("Umumiy o'rta ta'lim maktabi", "Umumiy o'rta ta'lim maktablari"), ('Musiqa maktabi', 'Musiqa maktablari'), ('Sport maktabi', 'Sport maktablari')], max_length=32),
        ),
        migrations.AlterField(
            model_name='historicalorganizationstatistics',
            name='type',
            field=models.CharField(choices=[("Maktabgacha ta'lim", "Maktabgacha ta'lim"), ("Umumiy o'rta ta'lim maktabi", "Umumiy o'rta ta'lim maktablari"), ('Musiqa maktabi', 'Musiqa maktablari'), ('Sport maktabi', 'Sport maktablari')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='education_type',
            field=models.CharField(choices=[("Maktabgacha ta'lim", "Maktabgacha ta'lim"), ("Umumiy o'rta ta'lim maktabi", "Umumiy o'rta ta'lim maktablari"), ('Musiqa maktabi', 'Musiqa maktablari'), ('Sport maktabi', 'Sport maktablari')], max_length=32),
        ),
        migrations.AlterField(
            model_name='organizationstatistics',
            name='type',
            field=models.CharField(choices=[("Maktabgacha ta'lim", "Maktabgacha ta'lim"), ("Umumiy o'rta ta'lim maktabi", "Umumiy o'rta ta'lim maktablari"), ('Musiqa maktabi', 'Musiqa maktablari'), ('Sport maktabi', 'Sport maktablari')], max_length=32, unique=True),
        ),
    ]
